language: node_js
node_js:
 - "11.4.0"
 
notifications:
  email: 
    false

services:
  - postgresql
  
before_install:
  - psql -c 'create database travis_ci_politico;' -U postgres
  - npm i -g npm@6.7.0
  
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
    
after_success:
- npm run coveralls
- npm run report-coverage