language: node_js
node_js:
 - "11.4.3"
 
notifications:
  email: 
    false
before_install:
  - npm i -g npm@6.7.0
  
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
    
after_success:
- npm run coveralls